import { deleteSecureSecret, getSecureSecret } from '../api/secure-storage'
import { decodePresentationBytes,encodePresentationBytes,type PresentationCodecId } from './presentationCodec'
const SETTINGS_KEY='pp_presentation_crypto_v1',LEGACY_SECRET_NAME='presentation-password-v1',PREFIX='ppx1|',AAD=new TextEncoder().encode('PaperPhonePlus-presentation-v1'),VERIFY='PaperPhonePlus-presentation-password-check-v1',iterations=210000
let password:string|null=null,backgroundAt:number|null=null,lockTimer:ReturnType<typeof setTimeout>|null=null
const keys=new Map<string,Promise<CryptoKey>>(),b64=(d:Uint8Array)=>btoa(String.fromCharCode(...d)),unb64=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0))
const presentationByPlaintext=new Map<string,string>()
export interface PresentationSettings{enabled:boolean;codec:PresentationCodecId;salt?:string;verifierIv?:string;verifier?:string;lockMinutes:5|15|30|60}
export function getPresentationSettings():PresentationSettings{const f:PresentationSettings={enabled:false,codec:'buddha',lockMinutes:5};try{return{...f,...(JSON.parse(localStorage.getItem(SETTINGS_KEY)||'null')||{})}}catch{return f}}
function save(s:PresentationSettings){localStorage.setItem(SETTINGS_KEY,JSON.stringify(s));window.dispatchEvent(new Event('paperphone:presentation-state-changed'))}
export function updatePresentationSettings(p:Partial<PresentationSettings>){save({...getPresentationSettings(),...p})}
const account=()=>{try{return JSON.parse(localStorage.getItem('user')||'null')?.id||null}catch{return null}}
async function derive(pass:string,salt:Uint8Array){const id=pass+':'+b64(salt);let k=keys.get(id);if(!k){k=crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']).then(m=>crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt,iterations},m,{name:'AES-GCM',length:256},false,['encrypt','decrypt']));keys.set(id,k)}return k}
async function makeVerifier(pass:string,salt:Uint8Array){const iv=crypto.getRandomValues(new Uint8Array(12)),key=await derive(pass,salt),v=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:AAD},key,new TextEncoder().encode(VERIFY)));return{verifierIv:b64(iv),verifier:b64(v)}}
export async function hydratePresentationCrypto(accountId:string){password=null;keys.clear();const legacy=await getSecureSecret(accountId,LEGACY_SECRET_NAME),s=getPresentationSettings();if(legacy&&s.enabled&&s.salt&&!s.verifier)save({...s,...await makeVerifier(legacy,unb64(s.salt))});await deleteSecureSecret(accountId,LEGACY_SECRET_NAME).catch(()=>{})}
export function isPresentationUnlocked(){return password!==null}
export function presentationCiphertextForPlaintext(text?:string){return text?presentationByPlaintext.get(text):undefined}
export async function enablePresentationCrypto(codec:PresentationCodecId,pass:string){if(pass.length<8)throw new Error('Password must be at least 8 characters');const salt=crypto.getRandomValues(new Uint8Array(16));keys.clear();password=pass;save({enabled:true,codec,salt:b64(salt),lockMinutes:getPresentationSettings().lockMinutes,...await makeVerifier(pass,salt)})}
export async function unlockPresentationCrypto(pass:string){const s=getPresentationSettings();if(!s.enabled||!s.salt||!s.verifier||!s.verifierIv)return false;password=null;keys.clear();try{const k=await derive(pass,unb64(s.salt)),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(s.verifierIv),additionalData:AAD},k,unb64(s.verifier));if(new TextDecoder().decode(plain)!==VERIFY)return false;password=pass;window.dispatchEvent(new Event('paperphone:presentation-state-changed'));return true}catch{keys.clear();return false}}
export async function disablePresentationCrypto(){const id=account();if(id)await deleteSecureSecret(id,LEGACY_SECRET_NAME).catch(()=>{});lockPresentationCrypto();const s=getPresentationSettings();save({enabled:false,codec:s.codec,lockMinutes:s.lockMinutes})}
export function lockPresentationCrypto(){password=null;keys.clear();if(lockTimer)clearTimeout(lockTimer);lockTimer=null;window.dispatchEvent(new Event('paperphone:presentation-state-changed'))}
export function handlePresentationAppState(active:boolean){if(active){if(backgroundAt&&Date.now()-backgroundAt>=getPresentationSettings().lockMinutes*60000)lockPresentationCrypto();backgroundAt=null;if(lockTimer)clearTimeout(lockTimer);lockTimer=null;return}backgroundAt=Date.now();if(lockTimer)clearTimeout(lockTimer);lockTimer=setTimeout(lockPresentationCrypto,getPresentationSettings().lockMinutes*60000)}
export async function protectPresentationText(text:string){const s=getPresentationSettings();if(!s.enabled)return text;if(!password||!s.salt)throw new Error('Presentation password is locked');const iv=crypto.getRandomValues(new Uint8Array(12)),key=await derive(password,unb64(s.salt)),encrypted=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:AAD},key,new TextEncoder().encode(text))),presented=`${PREFIX}${s.codec}|${s.salt}|${b64(iv)}|${encodePresentationBytes(encrypted,s.codec)}`;presentationByPlaintext.set(text,presented);return presented}
export async function unprotectPresentationText(text:string){if(!text.startsWith(PREFIX)||!password)return text;try{const[,codec,salt,iv,payload]=text.split('|'),key=await derive(password,unb64(salt)),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(iv),additionalData:AAD},key,decodePresentationBytes(payload,codec as PresentationCodecId)),result=new TextDecoder().decode(plain);presentationByPlaintext.set(result,text);return result}catch{return text}}
